version: '3'
services:
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=daily_advisor
        container_name: POSTGRES

    dailyadvisor-api:
        container_name: DailyAdvisor-API
        volumes:
            - ./DailyAdvisor-API:/DailyAdvisor-API
        build: 
            context: .
            dockerfile: ./DailyAdvisor-API/dev.Dockerfile
        ports:
            - "8091:8091"
        depends_on:
            - db

    dailyadvisor-pwa:
        container_name: DailyAdvisor-PWA
        volumes:
            - ./DailyAdvisor-PWA:/DailyAdvisor-PWA
        build: 
            context: .
            dockerfile: ./DailyAdvisor-PWA/dev.Dockerfile
        ports:
            - "3000:3000"
